---
- name: Configure webserver with nginx
  hosts: webservers
  become: True
  tasks:
    - name: install nginx
      package: name=nginx update_cache=yes

    - name: copy nginx config file
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default

    - name: enable config
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link
    - name: copy index.html
      template: >
        src=index.html.j2 
        dest=/usr/share/nginx/html/index.html
    - name: restart nginx
      service: name=nginx state=restarted